backend/urls.py
from django.contrib import admin
from django.urls import include, path

from .api import api


urlpatterns = [
    path('', include('core.urls')),
    path('', include('bookstore.urls', namespace='bookstore')),
    path('api/v2/', api.urls),
    path('admin/', admin.site.urls),
]

bookstore/urls.py
from django.urls import include, path
from rest_framework import routers

from bookstore import views as v
from bookstore.api_drf.viewsets import (
    AuthorViewSet,
    BookViewSet,
    PublisherViewSet
)

app_name = 'bookstore'

router = routers.DefaultRouter()

router.register(r'authors', AuthorViewSet)
router.register(r'publishers', PublisherViewSet)
router.register(r'books', BookViewSet)

authors_urlpatterns = [
    path('', v.AuthorListView.as_view(), name='author_list'),
    path('<int:pk>/', v.AuthorDetailView.as_view(), name='author_detail'),
    path('create/', v.AuthorCreateView.as_view(), name='author_create'),
    path('<int:pk>/update/', v.AuthorUpdateView.as_view(), name='author_update'),
    path('<int:pk>/delete/', v.AuthorDeleteView.as_view(), name='author_delete'),
]

publishers_urlpatterns = [
    path('', v.PublisherListView.as_view(), name='publisher_list'),
    path('<int:pk>/', v.PublisherDetailView.as_view(), name='publisher_detail'),
    path('create/', v.PublisherCreateView.as_view(), name='publisher_create'),
    path('<int:pk>/update/', v.PublisherUpdateView.as_view(), name='publisher_update'),
    path('<int:pk>/delete/', v.PublisherDeleteView.as_view(), name='publisher_delete'),
]

books_urlpatterns = [
    path('', v.BookListView.as_view(), name='book_list'),
    path('<int:pk>/', v.BookDetailView.as_view(), name='book_detail'),
    path('create/', v.BookCreateView.as_view(), name='book_create'),
    path('<int:pk>/update/', v.BookUpdateView.as_view(), name='book_update'),
    path('<int:pk>/delete/', v.BookDeleteView.as_view(), name='book_delete'),
]

urlpatterns = [
    path('api/v1/bookstore/', include(router.urls)),
    path('author/', include(authors_urlpatterns)),
    path('publisher/', include(publishers_urlpatterns)),
    path('book/', include(books_urlpatterns)),
]

core/urls.py
from django.urls import path

from .views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

bookstore/models.py
from django.db import models
from django.urls import reverse_lazy


class Author(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'Autor'
        verbose_name_plural = 'Autores'

    def get_absolute_url(self):
        return reverse_lazy('bookstore:author_detail', kwargs={'pk': self.pk})


class Publisher(models.Model):
    name = models.CharField(max_length=50, unique=True)
    score = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'Editora'
        verbose_name_plural = 'Editoras'

    def get_absolute_url(self):
        return reverse_lazy('bookstore:publisher_detail', kwargs={'pk': self.pk})


class Book(models.Model):
    name = models.CharField(max_length=100)
    isbn = models.CharField(max_length=13)
    rating = models.DecimalField(max_digits=5, decimal_places=2, null=True, default=0.0)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, null=True)
    price = models.DecimalField(max_digits=5, decimal_places=2, null=True, default=0.0)
    stock = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'Livro'
        verbose_name_plural = 'Livros'

    def get_absolute_url(self):
        return reverse_lazy('bookstore:book_detail', kwargs={'pk': self.pk})

bookstore/forms.py
from django import forms

from .models import Author, Book, Publisher


class _BaseModelForm(forms.ModelForm):
    required_css_class = 'required'

    def __init__(self, *args, **kwargs):
        super(_BaseModelForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class AuthorForm(_BaseModelForm):

    class Meta:
        model = Author
        fields = '__all__'


class PublisherForm(_BaseModelForm):

    class Meta:
        model = Publisher
        fields = '__all__'


class BookForm(_BaseModelForm):

    class Meta:
        model = Book
        fields = '__all__'

bookstore/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView
)

from .forms import AuthorForm, BookForm, PublisherForm
from .models import Author, Book, Publisher


class AuthorListView(ListView):
    model = Author
    paginate_by = 20


class AuthorDetailView(DetailView):
    model = Author


class AuthorCreateView(CreateView):
    model = Author
    form_class = AuthorForm


class AuthorUpdateView(UpdateView):
    model = Author
    form_class = AuthorForm


class AuthorDeleteView(DeleteView):
    model = Author
    success_url = reverse_lazy('bookstore:author_list')


class PublisherListView(ListView):
    model = Publisher
    paginate_by = 20


class PublisherDetailView(DetailView):
    model = Publisher


class PublisherCreateView(CreateView):
    model = Publisher
    form_class = PublisherForm


class PublisherUpdateView(UpdateView):
    model = Publisher
    form_class = PublisherForm


class PublisherDeleteView(DeleteView):
    model = Publisher
    success_url = reverse_lazy('bookstore:publisher_list')


class BookListView(ListView):
    model = Book
    paginate_by = 20


class BookDetailView(DetailView):
    model = Book


class BookCreateView(CreateView):
    model = Book
    form_class = BookForm


class BookUpdateView(UpdateView):
    model = Book
    form_class = BookForm


class BookDeleteView(DeleteView):
    model = Book
    success_url = reverse_lazy('bookstore:book_list')

core/views.py
from django.shortcuts import render


def index(request):
    template_name = 'index.html'
    return render(request, template_name)

bookstore/templates/bookstore/author_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Deletar Autor</h1>

  <div class="cols-6">
    <form action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}
        <p>Deseja deletar {{ object }} ?</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Sim</button>
          <a class="btn btn-danger" href="{% url 'bookstore:author_list' %}">Não</a>
        </div>
      </div>
    </form>
  </div>

{% endblock content %}

bookstore/templates/bookstore/author_detail.html
{% extends "base.html" %}

{% block content %}

<h1>Detalhes do Autor</h1>

<ul>
  <li><b>Nome:</b> {{ object.name }}</li>
</ul>

{% endblock content %}

bookstore/templates/bookstore/author_form.html
{% extends "base.html" %}

{% block content %}

  <h1>Adiciona Autor</h1>

  <div class="cols-6">
    <form class="form-horizontal" action="." method="POST" enctype="multipart/form-data">
      <div class="col-sm-6">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </form>
  </div>

{% endblock content %}

bookstore/templates/bookstore/author_list.html
{% extends "base.html" %}

{% block content %}

<h1>
  Lista de Autores
  <a href="{% url 'bookstore:author_create' %}" class="btn btn-primary">
    <i class="fa fa-plus"></i>
    Adicionar
  </a>
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
      <tr>
        <td>
          <a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
        </td>
        <td>
          <a href="{% url 'bookstore:author_update' object.pk %}">
            <i class="fa fa-edit"></i>
          </a>
          <a href="{% url 'bookstore:author_delete' object.pk %}" style="padding-left: 7px">
            <i class="fa fa-close no"></i>
          </a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% include "includes/pagination.html" %}

{% endblock content %}

bookstore/templates/bookstore/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Deletar Livro</h1>

  <div class="cols-6">
    <form action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}
        <p>Deseja deletar {{ object }} ?</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Sim</button>
          <a class="btn btn-danger" href="{% url 'bookstore:book_list' %}">Não</a>
        </div>
      </div>
    </form>
  </div>

{% endblock content %}

bookstore/templates/bookstore/book_detail.html
{% extends "base.html" %}

{% block content %}

<h1>Detalhes do Livro</h1>

<ul>
  <li><b>Nome:</b> {{ object.name }}</li>
  <li><b>ISBN:</b> {{ object.isbn }}</li>
  <li><b>Pontuação:</b> {{ object.rating }}</li>
  <li><b>Autores:</b> {{ object.authors.all|join:", " }}</li>
  <li><b>Editora:</b> {{ object.publisher }}</li>
  <li><b>Preço:</b> {{ object.price }}</li>
  <li><b>Estoque:</b> {{ object.stock }}</li>
</ul>

{% endblock content %}

bookstore/templates/bookstore/book_form.html
{% extends "base.html" %}

{% block content %}

  <h1>Adiciona Livro</h1>

  <div class="cols-6">
    <form class="form-horizontal" action="." method="POST" enctype="multipart/form-data">
      <div class="col-sm-6">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </form>
  </div>

{% endblock content %}

bookstore/templates/bookstore/book_list.html
{% extends "base.html" %}

{% block content %}

<h1>
  Lista de Livros
  <a href="{% url 'bookstore:book_create' %}" class="btn btn-primary">
    <i class="fa fa-plus"></i>
    Adicionar
  </a>
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>ISBN</th>
      <th>Pontuação</th>
      <th>Autores</th>
      <th>Editora</th>
      <th>Preço</th>
      <th>Estoque</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
      <tr>
        <td>
          <a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
        </td>
        <td>{{ object.isbn }}</td>
        <td>{{ object.rating }}</td>
        <td>{{ object.authors.all|join:", " }}</td>
        <td>{{ object.publisher }}</td>
        <td>{{ object.price }}</td>
        <td>{{ object.stock }}</td>
        <td>
          <a href="{% url 'bookstore:book_update' object.pk %}">
            <i class="fa fa-edit"></i>
          </a>
          <a href="{% url 'bookstore:book_delete' object.pk %}" style="padding-left: 7px">
            <i class="fa fa-close no"></i>
          </a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% include "includes/pagination.html" %}

{% endblock content %}

bookstore/templates/bookstore/publisher_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Deletar Editora</h1>

  <div class="cols-6">
    <form action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}
        <p>Deseja deletar {{ object }} ?</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Sim</button>
          <a class="btn btn-danger" href="{% url 'bookstore:publisher_list' %}">Não</a>
        </div>
      </div>
    </form>
  </div>

{% endblock content %}

bookstore/templates/bookstore/publisher_detail.html
{% extends "base.html" %}

{% block content %}

<h1>Detalhes da Editora</h1>

<ul>
  <li><b>Nome:</b> {{ object.name }}</li>
  <li><b>Pontos:</b> {{ object.score }}</li>
</ul>

{% endblock content %}

bookstore/templates/bookstore/publisher_form.html
{% extends "base.html" %}

{% block content %}

  <h1>Adiciona Editora</h1>

  <div class="cols-6">
    <form class="form-horizontal" action="." method="POST" enctype="multipart/form-data">
      <div class="col-sm-6">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </form>
  </div>

{% endblock content %}

bookstore/templates/bookstore/publisher_list.html
{% extends "base.html" %}

{% block content %}

<h1>
  Lista de Editoras
  <a href="{% url 'bookstore:publisher_create' %}" class="btn btn-primary">
    <i class="fa fa-plus"></i>
    Adicionar
  </a>
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Pontos</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    {% for object in object_list %}
      <tr>
        <td>
          <a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
        </td>
        <td>{{ object.score }}</td>
        <td>
          <a href="{% url 'bookstore:publisher_update' object.pk %}">
            <i class="fa fa-edit"></i>
          </a>
          <a href="{% url 'bookstore:publisher_delete' object.pk %}" style="padding-left: 7px">
            <i class="fa fa-close no"></i>
          </a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% include "includes/pagination.html" %}

{% endblock content %}

core/templates/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <title>Django</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  {% block css %}{% endblock css %}

</head>

<body>
  <div class="container">
    {% include "includes/nav.html" %}
    {% block content %}{% endblock content %}
  </div>

  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <!-- Bootstrap core JS -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>

</html>

core/templates/includes/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'core:index' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bookstore:author_list' %}">Autores</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bookstore:publisher_list' %}">Editoras</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bookstore:book_list' %}">Livros</a>
      </li>
    </ul>
  </div>
</nav>

core/templates/includes/pagination.html
<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
      {% endif %}

      {% for pg in page_obj.paginator.page_range %}
        <!-- Sempre mostra as 3 primeiras e 3 últimas páginas -->
        {% if pg == 1 or pg == 2 or pg == 3 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' or pg == page_obj.paginator.num_pages|add:'-2' %}
            {% if page_obj.number == pg %}
            <li class="page-item active"><a class="page-link" href="?page={{ pg }}
                {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ pg }}
                {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a>
            </li>
            {% endif %}
        {% else %}
          {% if page_obj.number == pg %}
            <li class="page-item active"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
          {% elif pg > page_obj.number|add:'-4' and pg < page_obj.number|add:'4' %}
            <!-- Mostra 3 páginas antes e 3 páginas depois da atual -->
            <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
          {% elif pg == page_obj.number|add:'-4' or pg == page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="">...</a></li>
          {% endif %}
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q }}">&raquo;</a></li>
      {% endif %}
    </ul>
  </div>
</div>

core/templates/index.html
{% extends "base.html" %}

{% block content %}
  <div class="jumbotron">
    <h1>Django</h1>
    <a href="" target="_blank">Github</a>
  </div>
{% endblock content %}